name: s2fft debug build

on:
  push:
    branches:
      - s2fft-debug-ci

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [linux64, linux64_cuda129, linux64_cuda130]
    runs-on: ubuntu-latest
    env:
      AZURE: "True"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build ${{ matrix.config }}
        run: python build-locally.py ${{ matrix.config }}
