name: s2fft debug build

on:
  push:
    branches:
      - s2fft-debug-ci

permissions:
  contents: read

jobs:
  linux64:
    runs-on: ubuntu-latest
    env:
      AZURE: "True"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build linux64
        run: python build-locally.py linux64
